# Generated by Django 6.0.8 on 2026-09-19 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sponsors.sponsorprofile'),
        ),
    ]
