# Generated by Django 6.0.8 on 2026-09-19 11:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_name', models.CharField(max_length=80)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(21), django.core.validators.MaxValueValidator(80)])),
                ('city', models.CharField(choices=[('Dar es Salaam', 'Dar es Salaam'), ('Arusha', 'Arusha'), ('Mwanza', 'Mwanza'), ('Dodoma', 'Dodoma'), ('Zanzibar', 'Zanzibar'), ('Mbeya', 'Mbeya'), ('Moshi', 'Moshi'), ('Morogoro', 'Morogoro'), ('Tanga', 'Tanga'), ('Iringa', 'Iringa'), ('Other', 'Other')], max_length=80)),
                ('lifestyle', models.CharField(help_text='Short tags, e.g. travel, cars, dinners', max_length=120)),
                ('preference', models.CharField(blank=True, help_text='Who he prefers to meet, e.g. 22-30, same city', max_length=120)),
                ('teaser', models.CharField(help_text='Shown before payment', max_length=180)),
                ('full_bio', models.TextField(help_text='Shown after the lady pays 15,000 TZS')),
                ('photo', models.ImageField(blank=True, upload_to='sponsors/')),
                ('accent', models.CharField(default='#C9A227', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_pay', 'Waiting listing payment'), ('live', 'Live'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('listing_paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['city', 'age'],
            },
        ),
        migrations.CreateModel(
            name='Unlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lady', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unlock', to='payments.payment')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='sponsors.sponsorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('lady', 'sponsor')},
            },
        ),
    ]
