# Generated by Django 6.0.8 on 2026-09-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('unlock', 'Unlock one sponsor'), ('listing', 'Post sponsor card')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('msisdn', models.CharField(max_length=15)),
                ('order_id', models.CharField(max_length=40, unique=True)),
                ('transid', models.CharField(blank=True, max_length=40)),
                ('selcom_reference', models.CharField(blank=True, max_length=80)),
                ('selcom_result', models.CharField(blank=True, max_length=40)),
                ('selcom_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Waiting Selcom'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
